### ISSUE TITLE
Use std::unordered_map<std::string, ...>

### ISSUE THREAD

**Issue by kkaefer** [mapbox/vector-tile#17]
It's typically faster.

**Comment by springmeyer** [comment]
I notice `std::map` is currently used only in layer decoding and the current benchmark suite we have is bottlenecked on feature decoding. So I modified the benchmark to only test layer decoding and getting features off the layer (rather than feature decoding):

```diff
diff --git a/bench/run.cpp b/bench/run.cpp
index 0b17b23..589b28d 100644
--- a/bench/run.cpp
+++ b/bench/run.cpp
@@ -16,12 +16,14 @@ static void decode_entire_tile(std::string const& buffer) {
         }
         for (std::size_t i=0;i<num_features;++i) {
             auto const feature = mapbox::vector_tile::feature(layer.getFeature(i),layer);
+            /*
             auto const& feature_id = feature.getID();
             if (!feature_id) {
                 throw std::runtime_error("Hit unexpected error decoding feature");
             }
             auto props = feature.getProperties();
             mapbox::vector_tile::points_arrays_type geom = feature.getGeometries<mapbox::vector_tile::points_arrays_type>(1.0);
+            */
             ++feature_count;
         }
     }
```

Running that on `master` gives (on OS X) times ranging from `1380 ms` to `1390 ms` (lower number is better). While testing on the [unordered branch](https://github.com/mapbox/vector-tile/pull/18) gives times ranging from `1448 ms` to  `1499ms`. So on OS X, at least, it appears this does not help performance. We should check on linux.

**Comment by kkaefer** [comment]
Thanks for running the benchmark. I can reproduce those results on Intel x86_64 as well, so it seems like `std::map` is actually faster here.
