### ISSUE TITLE
Phase 2 decoding

### ISSUE THREAD

**Issue by springmeyer** [mapbox/vector-tile#3]
Plan:

  - Write decoding utility functions to unpack vector tiles, in C++, into the feature+geometry structure of https://github.com/mapbox/geometry.hpp
   - Unpacks into tile coordinates, no assumed projection. 
  - Primary goal is to have this library be used in Mapbox GL native
  - Secondary goal is to have this library be used in mapnik-vector-tile and tippecanoe.
  - Depends on #2, [protozero](https://github.com/mapbox/protozero), [geometry.hpp](https://github.com/mapbox/geometry.hpp), [evilmvt fixtures](https://github.com/mapbox/evilmvt), and happymvt fixtures.
   - Uses latest protozero features: `-DPROTOZERO_STRICT_API`
  - Only supports v2 vector tiles (not v1)
  - Will be packaged in mason, able to be pulled back into mapbox-gl-native like geometry.hpp
  - Will be generic code suitable to be plugged back into/replace parts of:
   - https://github.com/mapbox/mapbox-gl-native/blob/master/src/mbgl/tile/vector_tile.cpp
   - https://github.com/mapbox/mapnik-vector-tile/blob/master/src/vector_tile_geometry_decoder.ipp
   - https://github.com/mapbox/mapnik-vector-tile/blob/master/src/vector_tile_featureset_pbf.ipp
   - https://github.com/mapbox/mapnik-vector-tile/blob/master/src/vector_tile_datasource_pbf.ipp

Longer term questions:

  - For mapnik-vector-tile to upgrade to this lib, Mapnik would likely need the ability to support non-projected tile coordinate data

**Comment by jfirebaugh** [comment]
Note that the collection of classes in mapbox-gl-native responsible for VT decoding -- `VectorTileData`, `VectorTileLayer`, and `VectorTileFeature` -- have some requirements that are fairly specific to mapbox-gl-native. It may be challenging to keep these requirements satisfied when using vector-tile as a dependency, while keeping vector-tile general-purpose.

* `VectorTileData`, `VectorTileLayer`, and `VectorTileFeature` must implement the abstract base classes `GeometryTileData`, `GeometryTileLayer`, and `GeometryTileFeature` respectively. This interface provides an abstraction over vector tile and GeoJSON sources so that that gl-native layout code is independent of the source type.
* These classes implement _lazy_ parsing -- a layer, feature, or feature geometry is kept as raw PBF bytes as long as possible, and parsed only when we know we'll actually need the structured representation. This is an important performance optimization, but it precludes using the "obvious" API where you have methods that return a `std::vector<vector_tile::layer>`, `std::vector<vector_tile::feature>`, and object constructors that eagerly parse everything.

**Comment by springmeyer** [comment]
Thanks @jfirebaugh - yes, agree that keeping lazy parsing is critical for performance. I think it is feasible to continue meeting the requirements of Mapbox GL while:

 - Avoiding any Mapbox GL code dependence
 - Providing generic APIs that other applications can use

This is my plan and my first iteration of using this library in Mapbox GL is now reviewable at https://github.com/mapbox/mapbox-gl-native/pull/6165.

**Comment by springmeyer** [comment]
Decoder added in https://github.com/mapbox/vector-tile/commit/8aaf1d045559701714a0758482db4934188dad02. Going to close this now and track next steps at these following tickets:

- testing: https://github.com/mapbox/vector-tile/issues/12 
- perf: https://github.com/mapbox/vector-tile/issues/13
